GET http://localhost:3000/user

###

GET http://localhost:3000/user/5df69d012f6f7d04f4dee6f1

###

POST http://localhost:3000/user
Content-Type: application/json

{
  "name": "Henrique",
  "email": "henrique.sonserina@hotmail.com"
}

###

PATCH http://localhost:3000/user/5df69d012f6f7d04f4dee6f1
Content-Type: application/json

{
  "name": "Novo Nome",
}

###

DELETE http://localhost:3000/user/5df69d012f6f7d04f4dee6f1