
DELETE http://localhost:3000/user/5df69d252f6f7d04f4dee6f2

###

GET http://localhost:3000/user

###

GET http://localhost:3000/user/5df69d252f6f7d04f4dee6f2

###

POST http://localhost:3000/user
Content-Type: application/json

{
  "name": "Henrique",
  "email": "henrique.sonserina@hotmail.com"
}

###

PATCH http://localhost:3000/user/5df6a9a9a4e8041ac8baa7c0
Content-Type: application/json

{
  "name": "Novo Nooome"
}